/*
 * Paquete encargado de mostrar todo el frontend relacionado a jBuscaminas
 */
package ymcris.ipc1.practica2.codengames.buscaminas.frontend;

import java.util.InputMismatchException;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import ymcris.ipc1.practica2.codengames.buscaminas.controllers.BuscaminasController;
import ymcris.ipc1.practica2.codengames.a.frontend.JPanelPersonalizado;
import ymcris.ipc1.practica2.codengames.a.frontend.JFMenuPrincipal;
import static ymcris.ipc1.practica2.codengames.a.frontend.JFMenuPrincipal.musicaMenu;

/**
 *
 * @author YmCris
 */
public class JFIniciarBuscaminas extends javax.swing.JFrame {

    private static String rutaImagenMenu = "/fondominas.png";
    public static BuscaminasController jBuscaminas = new BuscaminasController();
    /**
     * Creates new form IniciarNuevaPartidaBuscaminas
     */
    public JFIniciarBuscaminas() {
        initComponents();
        JPanelPersonalizado panelDiseñado = new JPanelPersonalizado(pnlInformacionBuscaminas, rutaImagenMenu);
        pnlInformacionBuscaminas.add(panelDiseñado).repaint();//Añade el panel diseñado al pnlMenu
        if (musicaMenu.isActive()) {
            musicaMenu.stop();
            musicaMenu.loop(Clip.LOOP_CONTINUOUSLY);
        }
        this.setResizable(false);//Para que no se deforme todo
        this.setLocationRelativeTo(null);//Lo centra
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInformacionBuscaminas = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtFilas = new javax.swing.JTextField();
        txtAvatar = new javax.swing.JTextField();
        txtMinas = new javax.swing.JTextField();
        txtColumnas = new javax.swing.JTextField();
        btnMusica = new javax.swing.JButton();
        btnInformación = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Nueva Partida Buscaminas");
        setBackground(new java.awt.Color(0, 0, 0));
        setName("jFrameInicioBuscaminas"); // NOI18N

        pnlInformacionBuscaminas.setBackground(new java.awt.Color(0, 0, 0));
        pnlInformacionBuscaminas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlInformacionBuscaminas.setPreferredSize(new java.awt.Dimension(1100, 800));

        lblTitulo1.setBackground(java.awt.SystemColor.activeCaptionText);
        lblTitulo1.setFont(new java.awt.Font("Snap ITC", 1, 100)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("BUSCAMINAS");
        lblTitulo1.setToolTipText("");
        lblTitulo1.setMaximumSize(new java.awt.Dimension(300, 300));
        lblTitulo1.setMinimumSize(new java.awt.Dimension(300, 300));
        lblTitulo1.setName(""); // NOI18N
        lblTitulo1.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CANTIDAD DE MINAS");

        jLabel2.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AVATAR");

        jLabel3.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FILAS DEL TABLERO");

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COLUMNAS DEL TABLERO");

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtFilas.setBackground(new java.awt.Color(0, 0, 0));
        txtFilas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFilas.setForeground(new java.awt.Color(255, 255, 255));
        txtFilas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtFilas.setCaretColor(new java.awt.Color(0, 0, 0));
        txtFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilasActionPerformed(evt);
            }
        });

        txtAvatar.setBackground(new java.awt.Color(0, 0, 0));
        txtAvatar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAvatar.setForeground(new java.awt.Color(255, 255, 255));
        txtAvatar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAvatar.setCaretColor(new java.awt.Color(0, 0, 0));

        txtMinas.setBackground(new java.awt.Color(0, 0, 0));
        txtMinas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMinas.setForeground(new java.awt.Color(255, 255, 255));
        txtMinas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMinas.setCaretColor(new java.awt.Color(0, 0, 0));

        txtColumnas.setBackground(new java.awt.Color(0, 0, 0));
        txtColumnas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtColumnas.setForeground(new java.awt.Color(255, 255, 255));
        txtColumnas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtColumnas.setCaretColor(new java.awt.Color(0, 0, 0));

        btnMusica.setBackground(new java.awt.Color(0, 0, 0));
        btnMusica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMusica.setText("M");
        btnMusica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });

        btnInformación.setBackground(new java.awt.Color(0, 0, 0));
        btnInformación.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInformación.setForeground(new java.awt.Color(255, 255, 255));
        btnInformación.setText("!");
        btnInformación.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInformación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformaciónActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("<-");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformacionBuscaminasLayout = new javax.swing.GroupLayout(pnlInformacionBuscaminas);
        pnlInformacionBuscaminas.setLayout(pnlInformacionBuscaminasLayout);
        pnlInformacionBuscaminasLayout.setHorizontalGroup(
            pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionBuscaminasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(431, 431, 431))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionBuscaminasLayout.createSequentialGroup()
                .addGroup(pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel2))
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3))
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionBuscaminasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInformación, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInformacionBuscaminasLayout.setVerticalGroup(
            pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInformación, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addGroup(pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)))
                .addGroup(pnlInformacionBuscaminasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMinas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInformacionBuscaminasLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)))
                .addGap(64, 64, 64)
                .addComponent(btnGuardar)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlInformacionBuscaminas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlInformacionBuscaminas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //1. Situación donde el usuario no ingresa nada y guarda.
        if (txtAvatar.getText().isBlank() || txtFilas.getText().isBlank() || txtColumnas.getText().isBlank() || txtMinas.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los espacios", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else {
            //2. Situación donde el usuario no introduce el tipo de entradas requeridas.
            try {
                if (jBuscaminas.todoEnOrden(txtAvatar.getText(), Integer.parseInt(txtFilas.getText()), Integer.parseInt(txtColumnas.getText()), Integer.parseInt(txtMinas.getText())) == true) {
                    System.out.println(" se crea el mapas");
                    musicaMenu.stop();
                    this.dispose();
                } else {//3. Situación en donde el usuario se ha equivocado al introducir un valor fuera de un rango
                    String mensajeError = jBuscaminas.encontrarErrores(txtAvatar.getText(), Integer.parseInt(txtFilas.getText()), Integer.parseInt(txtColumnas.getText()), Integer.parseInt(txtMinas.getText()));
                    JOptionPane.showMessageDialog(null, mensajeError, "ERROR", JOptionPane.WARNING_MESSAGE);
                }
            } catch (InputMismatchException | NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Debes colocar el tipo de datos adecuados", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        if (musicaMenu.isActive()) {
            musicaMenu.stop();
        } else if (!musicaMenu.isActive()) {
            musicaMenu.stop();
            musicaMenu.loop(Clip.LOOP_CONTINUOUSLY);
        }
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void btnInformaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformaciónActionPerformed
        JOptionPane.showMessageDialog(null, "¡No Toques Las Minas!", "Buscaminas", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnInformaciónActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        musicaMenu.stop();
        JFMenuPrincipal menu = new JFMenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilasActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInformación;
    private javax.swing.JButton btnMusica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel pnlInformacionBuscaminas;
    private javax.swing.JTextField txtAvatar;
    private javax.swing.JTextField txtColumnas;
    private javax.swing.JTextField txtFilas;
    private javax.swing.JTextField txtMinas;
    // End of variables declaration//GEN-END:variables
}
